version: '3'
services:
  db:
    image: postgres:16
    ports:
      - 3306:3306
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile.local
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    tty: true
    stdin_open: true
    ports:
      - '3000:3000'
    volumes: 
      - ./backend:/app
    environment:
      - GPT_ACCESS_TOKEN=${GPT_ACCESS_TOKEN}
      - REDIS_URL=${REDIS_URL}
      - CLAUDE_ACCESS_TOKEN=${CLAUDE_ACCESS_TOKEN}
    restart: always
    depends_on:
      - db
  frontend: 
    build:
      context: ./frontend/
      dockerfile: Dockerfile.local
    volumes:
      - ./frontend:/app
    command: bash -c "npm uninstall next && npm install next && yarn dev -p 8080"
    ports:
      - "8080:8080"
    
volumes:
  pg_data:
